[build]
  publish = "dist/confin"
  command = "ng build --prod"

[[redirects]]
  from = "/de/*"
  to = "/de/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
   from = "/"
   to = "/de"
   status = 302
   conditions = {Language = ["de"]}

[[redirects]]
   from = "/"
   to = "/en"
   status = 302
   conditions = {Language = ["en"]}

[[redirects]]
   from = "/"
   to = "/en"
   status = 302
